ludeeus/pyhaversion

.vscode/settings.json
example.py
pyhaversion/consts.py

Add Raspberry Pi 4

---

setup.py

fixes https://github.com/ludeeus/pyhaversion/issues/14
fixes https://git.edevau.net/onkelbeh/HomeAssistantRepository/issues/179

setup.py: don't try to install 'tests' package

---

.github/workflows/actions.yml
README.md
example.py
setup.py

Add test installation action

---

pyhaversion/consts.py
pyhaversion/docker.py

Add generic-x86-64 machine support which will replace intel-nuc long
term. Also add ODROID-C4 container image information.
- This PR is related to issue: https://github.com/home-assistant/core/pull/47131

Add generic-x86-64 machine support

---

.github/workflows/actions.yml
README.md
pyhaversion/container.py
setup.py
tests/test_container.py

Fix beta container version

---

pyhaversion/pypi.py

https://github.com/home-assistant/core/issues/57374

Fix PyPi sort

---

requirements.txt
setup.py

Bump awesomeversion

---

.github/workflows/actions.yml
pyhaversion/__init__.py
pyhaversion/base.py
pyhaversion/container.py
pyhaversion/haio.py
pyhaversion/local.py
pyhaversion/pypi.py
pyhaversion/supervisor.py
pyhaversion/version.py
tests/test_container.py
tests/test_haio.py

Cleanup classes

---

pyhaversion/base.py

Use default channel

---

.github/workflows/release.yml
pyhaversion/container.py
pyhaversion/haio.py
pyhaversion/pypi.py
pyhaversion/supervisor.py
requirements.txt
setup.py

Remove async_timeout

---

pyhaversion/container.py
pyhaversion/haio.py
pyhaversion/local.py
pyhaversion/pypi.py
pyhaversion/supervisor.py
pyhaversion/version.py
tests/test_pypi.py

Fix sources

---

example.py
pyhaversion/__init__.py
pyhaversion/base.py
pyhaversion/exceptions.py
pyhaversion/supervisor.py
pyhaversion/version.py
tests/test_supervisor.py
tests/test_version.py

Add Etag support for HaVersionSupervisor

---

pyhaversion/base.py
pyhaversion/local.py

Always return None for local version_data

---

example.py
pyhaversion/pypi.py
tests/test_haio.py
tests/test_pypi.py

Add Etag support for HaVersionPypi

---

pyhaversion/container.py
pyhaversion/pypi.py
tests/test_container.py
tests/test_pypi.py
tests/test_supervisor.py
tests/test_version.py

Handle KeyError in container parser

---

pyhaversion/haio.py
tests/test_haio.py

To handle https://github.com/home-assistant/core/issues/69435

Handle bad JSON

---

pyhaversion/consts.py

User Agent typo

---

.devcontainer.json
pyhaversion/consts.py

Backport `StrEnum` from python 3.11.
- This PR fixes or closes issue: fixes #120

Backport StrEnum from 3.11

---

.github/workflows/actions.yml
README.md

Changes the Python versions used in GitHub actions.
Replaces #119

Change testing to Python 3.10 -> 3.11

---

pyhaversion/container.py

As Home Assistant is no longer updating the images, there is no need to still support it here.

Remove image handling from container source

---

pyhaversion/base.py
pyhaversion/haio.py
pyhaversion/local.py
pyhaversion/pypi.py
pyhaversion/supervisor.py

As all (without local) needs this, it can be handled by the base class.

Cleanup input validation

---

.github/workflows/release.yml

Move release action to OIDC with attestation

---

pyhaversion/base.py
pyhaversion/consts.py
pyhaversion/container.py
pyhaversion/haio.py
pyhaversion/local.py
pyhaversion/pypi.py
pyhaversion/supervisor.py
pyhaversion/version.py
tests/test_container.py
tests/test_local.py
tests/test_pypi.py
tests/test_supervisor.py

Simplify handling of data

---

.pre-commit-config.yaml
pyhaversion/base.py
pyhaversion/container.py
pyhaversion/haio.py
pyhaversion/local.py
pyhaversion/pypi.py
pyhaversion/supervisor.py
pyhaversion/version.py
pyproject.toml
scripts/lint

- x ] Code quality improvements to existing code or addition of tests

Add strict type check with mypy

---

.devcontainer.json
.github/PULL_REQUEST_TEMPLATE.md
.pre-commit-config.yaml
example.py
poetry.lock
pyhaversion/base.py
pyhaversion/consts.py
pyhaversion/container.py
pyhaversion/haio.py
pyhaversion/local.py
pyhaversion/pypi.py
pyhaversion/supervisor.py
pyhaversion/version.py
pyproject.toml
scripts/lint
tests/conftest.py
tests/test_container.py
tests/test_haio.py
tests/test_local.py
tests/test_pypi.py
tests/test_supervisor.py
tests/test_version.py

Move to ruff

---

.github/workflows/actions.yml

Add testing with python 3.13

---

.github/workflows/actions.yml
.github/workflows/release-drafter.yml

Add minimum permissions in workflows

---

.github/workflows/actions.yml
.github/workflows/release-drafter.yml
.github/workflows/release.yml

Set SHA for external actions
